context:
  name: outlines-core
  version: "0.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/outlines_core-${{ version }}.tar.gz
  sha256: 3e44c09e8138adcd0b05eb8748a5bba912b51127ce03ad37f8fee53324a36d34

build:
  number: 1
  script:
    # NOTE: Switch to `script.content` and `script.env` once
    # https://github.com/prefix-dev/rattler-build/pull/1353 is merged.
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ "export OPENSSL_DIR=${PREFIX}" if unix }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools >=45
        - setuptools-scm >=6.2
        - setuptools-rust

    - ${{ compiler('rust') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - setuptools-rust
    - pip
    - ${{ "openssl" if unix }}
  run:
    - python
    - jsonschema

tests:
  - python:
      imports:
        - outlines_core
      pip_check: true

  # NOTE: disable the test for linux-ppc64le since pytorch is not
  # available. See https://github.com/conda-forge/pytorch-cpu-feedstock/pull/255
  - if: not (linux and ppc64le)
    then:
      requirements:
        run:
          - pytest
          - pytest-benchmark
          - pytest-mock
          - scipy
          - numpy
          - pytorch
          - pydantic
          - transformers
          - datasets
          - sentencepiece
      files:
        source:
          - tests/
      script:
        # NOTE: remove test_serialization.py since it imports the tests folder
        # which is a bad practice and raise an error here.
        - pytest -vvv tests/ --ignore=tests/fsm/test_serialization.py --deselect tests/test_guide.py::test_str_and_bytes_produce_the_same
        # TODO: remove the preceding deselect on the next release
        # (Fixed by https://github.com/dottxt-ai/outlines-core/pull/175)

about:
  summary: Structured Text Generation in Rust
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/dottxt-ai/outlines-core
  repository: https://github.com/dottxt-ai/outlines-core

extra:
  recipe-maintainers:
    - hadim
    - maresb
